const images = {
  logoWhiteBG: require('./justoLogoWhiteBG.png'),
  emailIcon: require('./email.png'),
  hiddenPassword: require('./hiddenPassword.png'),
  showPassword: require('./showPassword.png'),
  check: require('./check.png'),
  menu: require('./menu.png'),
  notification: require('./notification.png'),
  user: require('./user.png'),
  logout: require('./logout.png'),
  dashboard: require('./dashboard.png'),
  setting: require('./setting.png'),
  support: require('./support.png'),
  event: require('./event.png'),
  report: require('./report.png'),
  chat: require('./chat.png'),
  lead: require('./lead.png'),
  property: require('./property.png'),
  agency: require('./agency.png'),
  leftArrow: require('./leftArrow.png'),
  qrCode: require('./qrCode.png'),
  rightArrow: require('./rightArrow.png'),
  link: require('./link.png'),
  filter: require('./filter.png'),
  loginBanner: require('./loginBanner.png'),
  backArrow: require('./backArrow.png'),
  forwardArrow: require('./forwardArrow.png'),
  close: require('./close.png'),
  downErrow: require('./downErrow.png'),
  buildings: require('./buildings.jpeg'),
};

export default images;
