export const ADD_USERS = 'ADD_USERS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_USERS = 'GET_USERS';
export const REGISTER_ADD_USERS = 'REGISTER_ADD_USERS';
export const REGISTER_ADD_ERROR = 'REGISTER_ADD_ERROR';
export const USERS_ERROR = 'USERS_ERROR'
export const TOKEN_GENRATE = 'TOKEN_GENRATE'
export const USER_LIST = 'USER_LIST'
export const USER_DETAIL = 'USER_DETAIL'
export const USER_FILTERDETAIL = 'USER_FILTERDETAIL'
export const EDIT_USER = 'EDIT_USER'
export const USERSTATUS_UPDATE = 'USERSTATUS_UPDATE'


// REGISTRATION

export const REGISTRATION_FORM = 'REGISTRATION_FORM'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'
export const REGISTRATION_UPDATE = 'REGISTRATION_UPDATE'


// MASTER
export const CREATE_MASTER = 'CREATE_MASTER'
export const GET_AMENITY = 'GET_AMENITY'
export const GET_CONFIGURATION = 'GET_CONFIGURATION'
export const GET_PROPERTY_TYPE = 'GET_PROPERTY_TYPE'
export const GET_INSENTIVE_TYPE = 'GET_INSENTIVE_TYPE'
export const MASTER_LIST = 'MASTER_LIST'
export const MASTER_ERROR = 'MASTER_ERROR'

// ROLE
export const GET_ROLE = 'GET_ROLE'
export const GET_MODULE = 'GET_MODULE'
export const MODULE_ERROR = 'MODULE_ERROR'
export const CREATE_MODULE = 'CREATE_MODULE'
export const ROLE_MODULES = 'ROLE_MODULES'
export const CREATE_ROLE = 'CREATE_ROLE'
export const ROLE_DETAIL = 'ROLE_DETAIL'
export const ROLE_ERROR = 'ROLE_ERROR'

// PROPERTY
export const PROPERTY_FORM = 'PROPERTY_FORM'
export const PROPERTY_FORM_UPDATE = 'PROPERTY_FORM_UPDATE'
export const ADD_PROPERTY = 'ADD_PROPERTY'
export const PROPERTY_LIST = 'PROPERTY_LIST'
export const PROPERTY_EDIT = 'PROPERTY_EDIT'
export const GETPROPERTY_DETAIL = 'GETPROPERTY_DETAIL'
export const PROPERTY_FILTER_LIST = 'PROPERTY_FILTER_LIST'
export const PROPERTY_STATUS_UPDATE = 'PROPERTY_STATUS_UPDATE'
export const PROPERTY_ERROR = 'PROPERTY_ERROR'

// FOLLOWUP START
export const GET_FOLLOWUP = 'GET_FOLLOWUP'
export const FOLLOWUP_ERROR = 'FOLLOWUP_ERROR'


// AGENT
export const AGENT_LIST = 'AGENCY_LIST'
export const AGENT_ERROR = 'AGENCY_ERROR'
export const ADD_AGENT = 'ADD_AGENT'
export const EDIT_AGENT = 'EDIT_AGENT'
export const GET_AGENT_DETAIL = 'GET_AGENT_DETAIL'
export const AGENT_STATUSUPDATE = 'AGENT_STATUSUPDATE'
export const ADD_AGENT_FORM = 'ADD_AGENT_FORM'


