export const ADD_USERS = 'ADD_USERS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_USERS = 'GET_USERS';
export const REGISTER_ADD_USERS = 'REGISTER_ADD_USERS';
export const REGISTER_ADD_ERROR = 'REGISTER_ADD_ERROR';
export const USERS_ERROR = 'USERS_ERROR'
export const TOKEN_GENRATE = 'TOKEN_GENRATE'
export const USER_LIST = 'USER_LIST'
export const USER_DETAIL = 'USER_DETAIL'
export const USER_FILTERDETAIL = 'USER_FILTERDETAIL'
export const EDIT_USER = 'EDIT_USER'
export const USERSTATUS_UPDATE = 'USERSTATUS_UPDATE'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_ERROR = 'FORGOT_ERROR'
export const FORGOT_NULL = 'FORGOT_NULL'
export const OTPVERIFY = 'OTPVERIFY'
export const OTPVERIFY_NULL = 'OTPVERIFY_NULL'
export const OTPVERIFY_ERROR = 'OTPVERIFY_ERROR'
export const RESENDOTP = 'RESENDOTP'
export const RESENDOTP_NULL = 'RESENDOTP_NULL'
export const RESENDOTP_ERROR = 'RESENDOTP_ERROR'
export const UPDATEPASSWORD = 'UPDATEPASSWORD'
export const UPDATEPASSWORD_ERROR = 'UPDATEPASSWORD_ERROR'
export const UPDATEPASSWORD_NULL = 'UPDATEPASSWORD_NULL'


// REGISTRATION

export const REGISTRATION_FORM = 'REGISTRATION_FORM'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'
export const REGISTRATION_UPDATE = 'REGISTRATION_UPDATE'
export const CREATE_CHANNEL_PARTNER = 'CREATE_CHANNEL_PARTNER'
export const CREATE_CHANNEL_PARTNER_ERROR = 'CREATE_CHANNEL_PARTNER_ERROR'
export const CHECK_EMAIL_MOBILE = 'CHECK_EMAIL_MOBILE'
export const CHECK_EMAIL_MOBILE_ERROR = 'CHECK_EMAIL_MOBILE_ERROR'
export const GET_SOURCING_MANAGER = 'GET_SOURCING_MANAGER'
export const GET_SOURCING_MANAGER_ERROR = 'GET_SOURCING_MANAGER_ERROR'


// MASTER
export const CREATE_MASTER = 'CREATE_MASTER'
export const GET_AMENITY = 'GET_AMENITY'
export const GET_CONFIGURATION = 'GET_CONFIGURATION'
export const GET_PROPERTY_TYPE = 'GET_PROPERTY_TYPE'
export const GET_INSENTIVE_TYPE = 'GET_INSENTIVE_TYPE'
export const MASTER_LIST = 'MASTER_LIST'
export const MASTER_ERROR = 'MASTER_ERROR'

// ROLE
export const GET_ROLE = 'GET_ROLE'
export const GET_MODULE = 'GET_MODULE'
export const MODULE_ERROR = 'MODULE_ERROR'
export const CREATE_MODULE = 'CREATE_MODULE'
export const ROLE_MODULES = 'ROLE_MODULES'
export const CREATE_ROLE = 'CREATE_ROLE'
export const ROLE_DETAIL = 'ROLE_DETAIL'
export const ROLE_ERROR = 'ROLE_ERROR'

// PROPERTY
export const PROPERTY_FORM = 'PROPERTY_FORM'
export const PROPERTY_FORM_UPDATE = 'PROPERTY_FORM_UPDATE'
export const ADD_PROPERTY = 'ADD_PROPERTY'
export const PROPERTY_LIST = 'PROPERTY_LIST'
export const PROPERTY_EDIT = 'PROPERTY_EDIT'
export const GETPROPERTY_DETAIL = 'GETPROPERTY_DETAIL'
export const PROPERTY_FILTER_LIST = 'PROPERTY_FILTER_LIST'
export const PROPERTY_STATUS_UPDATE = 'PROPERTY_STATUS_UPDATE'
export const PROPERTY_ERROR = 'PROPERTY_ERROR'

// FOLLOWUP START
export const GET_FOLLOWUP_LIST = 'GET_FOLLOWUP'
export const FOLLOWUP_ERROR = 'FOLLOWUP_ERROR'
export const FOLLOWUP_DETAILS = 'FOLLOWUP_DETAILS'
export const FOLLOWUP_DETAILS_ERROR = 'FOLLOWUP_DETAILS_ERROR'
export const UPDATE_FOLLOWUP = 'UPDATE_FOLLOWUP'
export const UPDATE_FOLLOWUP_ERROR = 'UPDATE_FOLLOWUP_ERROR'
export const REMOVE_FOLLOWUP_DATA = 'REMOVE_FOLLOWUP_DATA'
export const ADD_FOLLOWUP = 'ADD_FOLLOWUP'
export const ADD_FOLLOWUP_ERROR = 'ADD_FOLLOWUP_ERROR'

// APPOINTMENT
export const GET_APPOINTMENT_LIST = 'GET_APPOINTMENT_LIST'
export const GET_APPOINTMENT_LIST_ERROR = 'GET_APPOINTMENT_LIST_ERROR'
export const GET_APPOINTMENT_DETAILS = 'GET_APPOINTMENT_DETAILS'
export const GET_APPOINTMENT_DETAILS_ERROR = 'GET_APPOINTMENT_DETAILS_ERROR'
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT'
export const ADD_APPOINTMENT_ERROR = 'ADD_APPOINTMENT_ERROR'
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT'
export const EDIT_APPOINTMENT_ERROR = 'EDIT_APPOINTMENT_ERROR'

// AGENT
export const AGENT_LIST = 'AGENCY_LIST'
export const AGENT_ERROR = 'AGENCY_ERROR'
export const ADD_AGENT = 'ADD_AGENT'
export const EDIT_AGENT = 'EDIT_AGENT'
export const GET_AGENT_DETAIL = 'GET_AGENT_DETAIL'
export const AGENT_STATUSUPDATE = 'AGENT_STATUSUPDATE'
export const ADD_AGENT_FORM = 'ADD_AGENT_FORM'


// Leads
export const VISITOR_LIST = 'VISITOR_LIST'
export const VISITOR_ERROR = 'VISITOR_ERROR'
export const ADD_VISITOR = 'ADD_VISITOR'
export const EDIT_VISITOR = 'EDIT_VISITOR'
export const GET_VISITOR_DETAIL = 'GET_VISITOR_DETAIL'
export const VISITOR_STATUSUPDATE = 'VISITOR_STATUSUPDATE'
export const ADD_VISITOR_FORM = 'ADD_VISITOR_FORM'
export const REMOVE_VISITOR = 'REMOVE_VISITOR'

// Update setting

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_ERROR = 'ADD_VISITOR_FORM'
export const CHANGEPASSWORD = 'CHANGEPASSWORD'
export const CHANGEPASSWORD_ERROR = 'CHANGEPASSWORD_ERROR'
export const CHANGEPASSWORD_NULL = 'CHANGEPASSWORD_NULL'





